### PR TITLE
[Proposal]:  Use styleguide for examples

### PR DESCRIPTION
**Pull request by smacker**
screen shot 2018-05-18 at 12 57 26

Instead of `demo` application, we may use [styleguidist](https://react-styleguidist.js.org/).
It allows to write markdown files with runnable examples.

To run it type
```
yarn start
```
in the directory with library.

If we agree to use it, I will convert the last example to md file and remove demo folder.

### CODE REVIEW

**Comment by bzz** [comment]
This looks really nice! 

Did not use styleguidists before, but love similar tooling i.e in https://github.com/storybooks/storybook

**Comment by carlosms** [comment]
It looks really good!
This implies that we will need to host the docs somewhere outside of github, right?

**Comment by smacker** [comment]
we can use github pages. `styleguidist build` can generate static version.

**Comment by smacker** [comment]
@bzz yep. Both project are mature and quite popular. The main difference in storybook you define _stories_ as __javascript__. And with styleguide as __markdown__.

I have update the PR. The main changes.

- Quckstart:
screen shot 2018-05-18 at 17 47 51

- Code in the controlled example is documented
- I decided not to port the last example from demo, but show only the one with text editor.
- Demo is removed

**Comment by smacker** [comment]
thanks a lot for comments! Fixed.

**Pull request merged**
